EVA04_DOTNET_V2/EVA04_DOTNET_V2/Models/ErrorViewModel.cs
namespace EVA04_DOTNET_V2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Models/Registro.cs
using System.ComponentModel.DataAnnotations;

namespace EVA04_DOTNET_V2.Models
{
    public class Registro
    {

        [Required(ErrorMessage = "MAIL ERROR")]
        public string Email { get; set; }


        [Required(ErrorMessage = "PASS ERROR")]
        [StringLength(50, ErrorMessage = "PASS LENGHT ERROR", MinimumLength = 5)]
        [DataType(DataType.Password)]
        [Display(Name = "PasswordOne")]
        public string Password { get; set; }


        [Required(ErrorMessage = "PASSWORDCONFIRMED ERROR")]
        [Compare("Password", ErrorMessage = "PASSWORDS DONT MATCH")]
        [DataType(DataType.Password)]
        [Display(Name = "PasswordOne")]
        public string ConfirmPassword { get; set; }


        [Required(ErrorMessage = "NAME ERROR")]
        public string Nombre { get; set; }


        [Required(ErrorMessage = "LASTNAME ERROR")]
        public string Apellido { get; set; }


    }
}

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Models/Usuario.cs
using Microsoft.AspNetCore.Identity;

namespace EVA04_DOTNET_V2.Models
{
    public class Usuario : IdentityUser
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
    }
}

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Controllers/CuentasController.cs
using EVA04_DOTNET_V2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EVA04_DOTNET_V2.Controllers
{
    public class CuentasController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public CuentasController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;

        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Registro()
        {
            Registro claseRegistro = new Registro();
            return View(claseRegistro);
        }

        [HttpPost]
        public async Task<ActionResult> Registro(Registro claseRegistro)
        {

            if (ModelState.IsValid)
            {
                var Usuario = new Usuario
                {
                    UserName = claseRegistro.Email,
                    Email = claseRegistro.Email,
                    Nombres = claseRegistro.Nombre,
                    Apellidos = claseRegistro.Apellido,
                };

                var resultado = await _userManager.CreateAsync(Usuario, claseRegistro.Password);
                await _signInManager.SignInAsync(Usuario, isPersistent: false);
                return RedirectToAction("Index", "Home");
            }
            return View(claseRegistro);
        }
    }
}

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Controllers/HomeController.cs
using EVA04_DOTNET_V2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EVA04_DOTNET_V2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Views/Cuentas/Registro.cshtml
@model Registro

@{
	ViewData["Title"] = "Registro de Usuario";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Registro de Usuarios</h1>
<form asp-controller="Cuentas" asp-action="Registro" method="post" role="form">

	<br />

	<div class="form-group">

		<label asp-for="Nombre" class="col-md-2"></label>

		<div class="col-md-10">

			<input asp-for="Nombre" class="form-control" />
			<span asp-validation-for="Nombre" class="text-danger"></span>
		</div>

	</div>

	<br />

	<div class="form-group">

		<label asp-for="Apellido" class="col-md-2"></label>

		<div class="col-md-10">

			<input asp-for="Apellido" class="form-control" />
			<span asp-validation-for="Apellido" class="text-danger"></span>
		</div>

	</div>

	<br />

	<div class="form-group">

		<label asp-for="Email" class="col-md-2"></label>

		<div class="col-md-10">

			<input asp-for="Email" class="form-control" />
			<span asp-validation-for="Email" class="text-danger"></span>
		</div>

	</div>

	<br />

	<div class="form-group">

		<label asp-for="Password" class="col-md-2"></label>

		<div class="col-md-10">

			<input asp-for="Password" class="form-control" />
			<span asp-validation-for="Password" class="text-danger"></span>
		</div>

	</div>

	<br />

	<div class="form-group">

		<label asp-for="ConfirmPassword" class="col-md-2"></label>

		<div class="col-md-10">

			<input asp-for="ConfirmPassword" class="form-control" />
			<span asp-validation-for="ConfirmPassword" class="text-danger"></span>
		</div>

	</div>

	<br /><br />

	<div class="form-group">
		<div class="col-md-10">
			<button type="submit" class="btn btn-success">Registrar</button>
		</div>
	</div>

</form>

@section Scripts{
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}

}

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EVA04_DOTNET_V2/EVA04_DOTNET_V2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EVA04_DOTNET_V2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EVA04_DOTNET_V2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EVA04_DOTNET_V2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuentas" asp-action="Registro">Registro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EVA04_DOTNET_V2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>